classes:
- system.linux.system.repo.ubuntu
- system.linux.system.repo.mcp.salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.salt.minion.cert.k8s_server
- system.reclass.storage.system.kubernetes_control_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- cluster.k8s-ha-contrail
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://gerrit.mcp.mirantis.net/salt-models/mcp-virtual-lab"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: ${_param:infra_config_deploy_address}
  salt:
    master:
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
  reclass:
    storage:
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
            deploy_address:
              value_template: <<node_deploy_ip>>
        infra_config:
          expression: <<node_hostname>>__startswith__cfg
          cluster_param:
            infra_config_address:
              value_template: <<node_control_ip>>
            infra_config_deploy_address:
              value_template: <<node_deploy_ip>>
            cluster_domain:
              value_template: <<node_domain>>
        kubernetes_control01:
          expression: <<node_hostname>>__equals__ctl01
          cluster_param:
            kubernetes_control_node01_address:
              value_template: <<node_control_ip>>
            kubernetes_control_node01_deploy_address:
              value_template: <<node_deploy_ip>>
        kubernetes_control02:
          expression: <<node_hostname>>__equals__ctl02
          cluster_param:
            kubernetes_control_node02_address:
              value_template: <<node_control_ip>>
            kubernetes_control_node02_deploy_address:
              value_template: <<node_deploy_ip>>
        kubernetes_control03:
          expression: <<node_hostname>>__equals__ctl03
          cluster_param:
            kubernetes_control_node03_address:
              value_template: <<node_control_ip>>
            kubernetes_control_node03_deploy_address:
              value_template: <<node_deploy_ip>>
        etcd_control01:
          expression: <<node_hostname>>__equals__ctl01
          cluster_param:
            etcd_control_node01_address:
              value_template: <<node_deploy_ip>>
        etcd_control02:
          expression: <<node_hostname>>__equals__ctl02
          cluster_param:
            etcd_control_node02_address:
              value_template: <<node_deploy_ip>>
        etcd_control03:
          expression: <<node_hostname>>__equals__ctl03
          cluster_param:
            etcd_control_node03_address:
              value_template: <<node_deploy_ip>>
        opencontrail_control01:
          expression: <<node_hostname>>__equals__ntw01
          cluster_param:
            opencontrail_control_node01_address:
              value_template: <<node_control_ip>>
        opencontrail_control02:
          expression: <<node_hostname>>__equals__ntw02
          cluster_param:
            opencontrail_control_node02_address:
              value_template: <<node_control_ip>>
        opencontrail_control03:
          expression: <<node_hostname>>__equals__ntw03
          cluster_param:
            opencontrail_control_node03_address:
              value_template: <<node_control_ip>>
        kubernetes_compute:
          expression: <<node_hostname>>__startswith__cmp
          node_class:
            value_template:
              - cluster.<<node_cluster>>.kubernetes.compute
      node:
        opencontrail_control_node01:
          params:
            rabbitmq_cluster_role: master
        opencontrail_control_node02:
          params:
            rabbitmq_cluster_role: slave
        opencontrail_control_node03:
          params:
            rabbitmq_cluster_role: slave
