classes:
  - system.linux.system.repo.mcp.salt
  - system.salt.master.pkg
  - system.salt.master.api
  - system.salt.minion.ca.salt_master
  - system.reclass.storage.salt
  - system.sphinx.server.doc.reclass
  - cluster.drivetrain-ha
parameters:
  salt:
    master:
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      environment:
        prd:
          formula:
            glusterfs:
              source: pkg
              name: salt-formula-glusterfs
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
  reclass:
    storage:
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
        infra_config:
          expression: <<node_hostname>>__equals__cid01
          cluster_param:
            infra_config_address:
              value_template: <<node_control_ip>>
            infra_config_deploy_address:
              value_template: <<node_deploy_ip>>
            cluster_domain:
              value_template: <<node_domain>>
            cicd_control_node_node01_address:
              value_template: <<node_control_ip>>
        cicd_control_node02:
          expression: <<node_hostname>>__equals__cid02
          cluster_param:
            cicd_control_node_node02_address:
              value_template: <<node_control_ip>>
        cicd_control_node03:
          expression: <<node_hostname>>__equals__cid03
          cluster_param:
            cicd_control_node03_address:
              value_template: <<node_control_ip>>
      node:
        cicd_control_node01:
          name: ${_param:cicd_control_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.cicd.control.master
          params:
            salt_master_host: 127.0.0.1
            linux_system_codename: xenial
            single_address: ${_param:cicd_control_node01_address}
            keepalived_vip_priority: 103
        cicd_control_node02:
          name: ${_param:cicd_control_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.cicd.control.slave
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:cicd_control_node02_address}
            keepalived_vip_priority: 102
            docker_swarm_role: worker
        cicd_control_node03:
          name: ${_param:cicd_control_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.cicd.control.slave
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:cicd_control_node03_address}
            keepalived_vip_priority: 101
            docker_swarm_role: worker

