classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker_legacy
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- cluster.k8s-ha-contrail.kubernetes.compute
- cluster.k8s-ha-contrail
parameters:
  _param:
    keepalived_vip_interface: vhost0
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      bind:
        host: ${_param:deploy_address}
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    common:
      addons:
        dashboard:
          enabled: ${_param:kubernetes_dashboard}
        helm:
          enabled: ${_param:kubernetes_helm_enabled}
        netchecker:
          enabled: ${_param:kubernetes_netchecker_enabled}
          agent_image: ${_param:kubernetes_netchecker_agent_image}
          server_image: ${_param:kubernetes_netchecker_server_image}
        contrail_network_controller:
          namespace: ${_param:kubernetes_addon_namespace}
          enabled: ${_param:kubernetes_contrail_network_controller}
          image: ${_param:kubernetes_contrail_network_controller_image}
        coredns:
          enabled: ${_param:kubernetes_coredns_enabled}
        externaldns:
          enabled: ${_param:kubernetes_externaldns_enabled}
          image: ${_param:kubernetes_externaldns_image}
          provider: ${_param:kubernetes_externaldns_provider}
    master:
      kubelet:
        address: ${_param:single_address}
      etcd:
        ssl:
          enabled: true
      network:
        etcd:
          ssl:
            enabled: true
      namespace:
        netchecker:
          enabled: true
      network:
        engine: opencontrail
        public_ip_range: 185.22.97.128/26
        public_network: default-domain:default-project:Public
        private_ip_range: 10.150.0.0/16
        config:
          api:
            host: ${_param:opencontrail_control_address}
